{
  flake.nixosModules.opencode = {
    lib,
    pkgs,
    ...
  }: let
    chromiumEntry = builtins.head (
      builtins.filter
      (name: lib.hasPrefix "chromium-" name)
      (builtins.attrNames pkgs.playwright-driver.browsers.entries)
    );
    chromiumExecutable = "${pkgs.playwright-driver.browsers}/${chromiumEntry}/chrome-linux64/chrome";
    playwrightMcpConfig = pkgs.writeText "opencode-playwright-mcp.json" (builtins.toJSON {
      browser.launchOptions.args = [
        "--class=opencode-playwright"
        "--install-autogenerated-theme=255,0,64"
      ];
    });
    opencode-playwright-icon = pkgs.runCommand "opencode-playwright-icon" {} ''
      install -d "$out/share/icons/hicolor/256x256/apps"
      ${pkgs.imagemagick}/bin/magick \
        ${pkgs.ungoogled-chromium}/share/icons/hicolor/256x256/apps/chromium.png \
        -colorspace gray \
        -fill '#ff0040' \
        -tint 100 \
        "$out/share/icons/hicolor/256x256/apps/opencode-playwright.png"
    '';
    opencode-playwright-desktop = pkgs.makeDesktopItem {
      name = "opencode-playwright";
      desktopName = "OpenCode Playwright";
      comment = "Browser controlled by OpenCode through Playwright MCP";
      exec = "${pkgs.coreutils}/bin/true";
      icon = "${opencode-playwright-icon}/share/icons/hicolor/256x256/apps/opencode-playwright.png";
      startupWMClass = "opencode-playwright";
      extraConfig.NoDisplay = "true";
    };
    opencode-playwright-mcp = pkgs.writeShellApplication {
      name = "opencode-playwright-mcp";
      runtimeInputs = [pkgs.playwright-mcp];
      text = ''
        unset PLAYWRIGHT_BROWSERS_PATH
        export PLAYWRIGHT_MCP_BROWSER=chrome
        export PLAYWRIGHT_MCP_EXECUTABLE_PATH=${chromiumExecutable}
        export PLAYWRIGHT_MCP_CONFIG=${playwrightMcpConfig}
        export PLAYWRIGHT_MCP_USER_DATA_DIR=/home/luc/.cache/ms-playwright/opencode-mcp
        export PLAYWRIGHT_MCP_OUTPUT_DIR=/home/luc/.cache/opencode/playwright-mcp
        exec playwright-mcp "$@"
      '';
    };
  in {
    environment.systemPackages = with pkgs; [
      opencode
      opencode-playwright-mcp
      opencode-playwright-icon
      opencode-playwright-desktop
      playwright-driver
    ];

    environment.sessionVariables = {
      OPENCODE_DISABLE_CHANNEL_DB = "1";
    };

    home-manager.users.luc.home.sessionVariables = {
      OPENCODE_DISABLE_CHANNEL_DB = "1";
    };

    home-manager.users.luc.home.file.".config/opencode/opencode.jsonc" = {
      source = ./opencode/opencode.jsonc;
      force = true;
    };

    home-manager.users.luc.home.file.".config/opencode/AGENTS.md" = {
      source = ./opencode/rules/AGENTS.md;
      force = true;
    };

    home-manager.users.luc.home.file.".config/opencode/rules/TYPESCRIPT.md" = {
      source = ./opencode/rules/TYPESCRIPT.md;
      force = true;
    };

    home-manager.users.luc.home.file.".config/opencode/agents/visual-qa.md" = {
      source = ./opencode/agents/visual-qa.md;
      force = true;
    };
  };
}
