_: {
  perSystem = {pkgs, ...}: let
    chromiumEntry = builtins.head (
      builtins.filter
      (name: pkgs.lib.hasPrefix "chromium-" name)
      (builtins.attrNames pkgs.playwright-driver.browsers.entries)
    );
    chromiumExecutable = "${pkgs.playwright-driver.browsers}/${chromiumEntry}/chrome-linux64/chrome";
    playwrightMcpChromium = pkgs.writeShellApplication {
      name = "chromium";
      text = ''
        exec ${chromiumExecutable} \
          --class=playwright-mcp \
          --install-autogenerated-theme=255,0,64 \
          "$@"
      '';
    };
    walletProvider = pkgs.writeText "dapp-wallet-provider.js" (builtins.readFile ./wallet-mcp/provider.js);
    py = pkgs.python3Packages;
    dappWalletMcpServer = py.buildPythonApplication {
      pname = "dapp-wallet-mcp-server";
      version = "0.1.0";
      format = "other";
      src = ./wallet-mcp/dapp-wallet-mcp.py;
      dependencies = [py.mcp];
      dontUnpack = true;
      installPhase = ''
        install -Dm755 "$src" "$out/bin/dapp-wallet-mcp-server"
      '';
    };
    playwrightMcpConfig = pkgs.writeText "playwright-mcp.json" (builtins.toJSON {
      # The sandboxes have separate PID namespaces, so Chromium cannot see the
      # profile lock of another sandbox, and a shared profile gets corrupted.
      browser.isolated = true;
      browser.initScript = [walletProvider];
    });
    playwrightMcpIcon = pkgs.runCommand "playwright-mcp-icon" {} ''
      install -d "$out/share/icons/hicolor/256x256/apps"
      ${pkgs.imagemagick}/bin/magick \
        ${pkgs.ungoogled-chromium}/share/icons/hicolor/256x256/apps/chromium.png \
        -colorspace gray \
        -fill '#ff0040' \
        -tint 100 \
        "$out/share/icons/hicolor/256x256/apps/playwright-mcp.png"
    '';
  in {
    packages = {
      inherit playwrightMcpChromium;
      playwright-mcp-icon = playwrightMcpIcon;

      dapp-wallet-mcp = pkgs.writeShellApplication {
        name = "dapp-wallet-mcp";
        runtimeInputs = [pkgs.foundry];
        text = ''
          exec ${dappWalletMcpServer}/bin/dapp-wallet-mcp-server
        '';
      };

      playwright-mcp-desktop = pkgs.makeDesktopItem {
        name = "playwright-mcp";
        desktopName = "Playwright MCP";
        comment = "Browser controlled through Playwright MCP";
        exec = "${pkgs.coreutils}/bin/true";
        icon = "${playwrightMcpIcon}/share/icons/hicolor/256x256/apps/playwright-mcp.png";
        startupWMClass = "playwright-mcp";
        extraConfig.NoDisplay = "true";
      };

      playwright-mcp = pkgs.writeShellApplication {
        name = "playwright-mcp";
        runtimeInputs = [pkgs.playwright-mcp];
        text = ''
          unset PLAYWRIGHT_BROWSERS_PATH
          export PLAYWRIGHT_MCP_BROWSER=chrome
          export PLAYWRIGHT_MCP_EXECUTABLE_PATH=${playwrightMcpChromium}/bin/chromium
          export PLAYWRIGHT_MCP_CONFIG=${playwrightMcpConfig}
          # The server starts in the project directory, which is the only
          # directory the sandbox binds writable.
          export PLAYWRIGHT_MCP_OUTPUT_DIR="$PWD/.tmp/screenshots"
          exec playwright-mcp "$@"
        '';
      };
    };
  };
}
