{...}: {
  perSystem = {pkgs, ...}: let
    chromiumEntry = builtins.head (
      builtins.filter
      (name: pkgs.lib.hasPrefix "chromium-" name)
      (builtins.attrNames pkgs.playwright-driver.browsers.entries)
    );
    chromiumExecutable = "${pkgs.playwright-driver.browsers}/${chromiumEntry}/chrome-linux64/chrome";
    playwrightMcpConfig = pkgs.writeText "playwright-mcp.json" (builtins.toJSON {
      browser.launchOptions.args = [
        "--class=playwright-mcp"
        "--install-autogenerated-theme=255,0,64"
      ];
    });
    playwrightMcpIcon = pkgs.runCommand "playwright-mcp-icon" {} ''
      install -d "$out/share/icons/hicolor/256x256/apps"
      ${pkgs.imagemagick}/bin/magick \
        ${pkgs.ungoogled-chromium}/share/icons/hicolor/256x256/apps/chromium.png \
        -colorspace gray \
        -fill '#ff0040' \
        -tint 100 \
        "$out/share/icons/hicolor/256x256/apps/playwright-mcp.png"
    '';
  in {
    packages = {
      playwright-mcp-icon = playwrightMcpIcon;

      playwright-mcp-desktop = pkgs.makeDesktopItem {
        name = "playwright-mcp";
        desktopName = "Playwright MCP";
        comment = "Browser controlled through Playwright MCP";
        exec = "${pkgs.coreutils}/bin/true";
        icon = "${playwrightMcpIcon}/share/icons/hicolor/256x256/apps/playwright-mcp.png";
        startupWMClass = "playwright-mcp";
        extraConfig.NoDisplay = "true";
      };

      playwright-mcp = pkgs.writeShellApplication {
        name = "playwright-mcp";
        runtimeInputs = [pkgs.playwright-mcp];
        text = ''
          unset PLAYWRIGHT_BROWSERS_PATH
          export PLAYWRIGHT_MCP_BROWSER=chrome
          export PLAYWRIGHT_MCP_EXECUTABLE_PATH=${chromiumExecutable}
          export PLAYWRIGHT_MCP_CONFIG=${playwrightMcpConfig}
          export PLAYWRIGHT_MCP_USER_DATA_DIR=/home/luc/.cache/ms-playwright/playwright-mcp
          export PLAYWRIGHT_MCP_OUTPUT_DIR=/home/luc/.cache/playwright-mcp
          exec playwright-mcp "$@"
        '';
      };
    };
  };
}
