{
 "title": "Missed Attestations",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "options": {
    "content": "\n# Missed Attestation Analysis\n\nA collection of metrics for analysing and\ndiagnosing missed attestations.\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Late blocks (Per Day)",
   "type": "stat",
   "description": "Number of unattestable (late) blocks over the last day",
   "gridPos": { "h": 6, "w": 2, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(beacon_block_delay_gossip_arrived_late_total[1d])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head Hit Ratio (1 Hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_simulator_head_attester_hit_total{}[1h]) /\n (increase(validator_monitor_attestation_simulator_head_attester_hit_total{}[1h]) +\n increase(validator_monitor_attestation_simulator_head_attester_miss_total{}[1h]))",
     "legendFormat": "{{instance}} - {{src}}"
    }
   ]
  },
  {
   "title": "Head Hit Ratio (1 Day)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_simulator_head_attester_hit_total{}[1d]) /\n (increase(validator_monitor_attestation_simulator_head_attester_hit_total{}[1d]) +\n increase(validator_monitor_attestation_simulator_head_attester_miss_total{}[1d]))",
     "legendFormat": "{{instance}} - {{src}}"
    }
   ]
  },
  {
   "title": "Head Hit Ratio (1 Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_simulator_head_attester_hit_total{}[7d]) /\n (increase(validator_monitor_attestation_simulator_head_attester_hit_total{}[7d]) +\n increase(validator_monitor_attestation_simulator_head_attester_miss_total{}[7d]))",
     "legendFormat": "{{instance}} - {{src}}"
    }
   ]
  },
  {
   "title": "Target Hit Ratio (1 Hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_simulator_target_attester_hit_total{}[1h]) /\n (increase(validator_monitor_attestation_simulator_target_attester_hit_total{}[1h]) +\n increase(validator_monitor_attestation_simulator_target_attester_miss_total{}[1h]))",
     "legendFormat": "{{instance}} - {{src}}"
    }
   ]
  },
  {
   "title": "Target Hit Ratio (1 Day)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_simulator_target_attester_hit_total{}[1d]) /\n (increase(validator_monitor_attestation_simulator_target_attester_hit_total{}[1d]) +\n increase(validator_monitor_attestation_simulator_target_attester_miss_total{}[1d]))",
     "legendFormat": "{{instance}} - {{src}}"
    }
   ]
  },
  {
   "title": "Target Hit Ratio (1 Week)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(validator_monitor_attestation_simulator_target_attester_hit_total{}[7d]) /\n (increase(validator_monitor_attestation_simulator_target_attester_hit_total{}[7d]) +\n increase(validator_monitor_attestation_simulator_target_attester_miss_total{}[7d]))",
     "legendFormat": "{{instance}} - {{src}}"
    }
   ]
  },
  {
   "title": "Block Delay Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Block Delay (Network + Processing)",
   "type": "timeseries",
   "description": "The total delay before setting this block as the current head.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "beacon_block_delay_total", "legendFormat": "Total Block Delay" }
   ]
  },
  {
   "title": "Component Time to Attestable",
   "type": "timeseries",
   "description": "All the components that consume time leading up to the earliest time the block can be attested to.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_attestable_slot_start",
     "legendFormat": "Attestable"
    },
    {
     "expr": "beacon_block_delay_available_slot_start",
     "legendFormat": "Available"
    },
    {
     "expr": "beacon_block_delay_observed_slot_start + beacon_block_delay_execution_time",
     "legendFormat": "Block Arrived and Verified"
    },
    {
     "expr": "beacon_blob_delay_all_observed_slot_start",
     "legendFormat": "Blobs Arrived"
    },
    {
     "expr": "beacon_block_delay_observed_slot_start",
     "legendFormat": "Block Arrived - Processing"
    },
    { "expr": "beacon_block_delay_gossip", "legendFormat": "Block Arrived - Gossip" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "options": {
    "content": "\n# Component Metrics\n\nThese metrics look at the contributing factors to block delays\n1. Time for EL to verify block\n2. Lighthouse's processing (attestable - available)\n3. Gossipsub verification - The time from recieving to repropagating on the network\n4. Time taken to import the block (DB and fork-choice related) \n\n\n\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "1. Execution Verifiction Time",
   "type": "timeseries",
   "description": "The time it took to ask the EL if the block is valid",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_execution_time",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "2. Time taken to be attestable from being available",
   "type": "timeseries",
   "description": "This is Lighthouse's processing from the time we received all the components on the network, to making the block available to attest to",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_attestable_slot_start - beacon_block_delay_available_slot_start",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "3. Gossip verification time",
   "type": "timeseries",
   "description": "The time it takes to verify a gossipsub block before repropagating",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_gossip_verification",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Import Time",
   "type": "timeseries",
   "description": "The time between the block being available and being imported in the chain",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "beacon_block_delay_imported_time",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Attestation Subnet Stability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Subscribed Peers Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "gossipsub_topic_peers_counts{hash!~\".*attester_slashing.*|.*beacon_aggregate_and_proof.*|.*beacon_block.*|.*proposer_slashing.*|.*voluntary_exit.*|.*sync_committee_contribution_and_proof.*|.*bls_to_execution.*|.*light_client.*|.*blob_sidecar.*|\"}",
     "legendFormat": "{{hash}}"
    }
   ]
  },
  {
   "title": "Queued Discovery Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "targets": [
    { "expr": "discovery_queue_size{}", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Failed Attestations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(gossipsub_failed_attestation_publishes_per_subnet[$__rate_interval])",
     "legendFormat": "Subnet: {{subnet}}"
    }
   ]
  }
 ]
}