# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  self,
  inputs,
  ...
}: {
  flake.nixosModules.fighterPhysical = {
    config,
    lib,
    pkgs,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = ["nvme" "ahci" "xhci_pci" "usb_storage" "usbhid" "sd_mod"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-amd"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/f43ce2fa-fe57-4ac3-98ee-e63bfd823647";
      fsType = "btrfs";
      options = ["subvol=@"];
    };

    fileSystems."/home" = {
      device = "/dev/disk/by-uuid/f43ce2fa-fe57-4ac3-98ee-e63bfd823647";
      fsType = "btrfs";
      options = ["subvol=@home"];
    };

    fileSystems."/nix" = {
      device = "/dev/disk/by-uuid/f43ce2fa-fe57-4ac3-98ee-e63bfd823647";
      fsType = "btrfs";
      options = ["subvol=@nix"];
    };

    fileSystems."/.snapshots" = {
      device = "/dev/disk/by-uuid/f43ce2fa-fe57-4ac3-98ee-e63bfd823647";
      fsType = "btrfs";
      options = ["subvol=@snapshots"];
    };

    fileSystems."/var/log" = {
      device = "/dev/disk/by-uuid/f43ce2fa-fe57-4ac3-98ee-e63bfd823647";
      fsType = "btrfs";
      options = ["subvol=@log"];
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/DF60-18D4";
      fsType = "vfat";
      options = ["fmask=0022" "dmask=0022"];
    };

    swapDevices = [];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
